routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\BrowseController;
use App\Http\Controllers\ReviewsController;
use App\Http\Controllers\SiteStatsController;
use App\Http\Controllers\AnimeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\LogoutController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\UserFavouriteListController;
use App\Http\Controllers\MyListController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\UserDetailController;
use App\Http\Controllers\UserAnimeStatusListController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\BlogPostController;
use App\Http\Controllers\Admin\CategoryController;

use App\Http\Controllers\SitemapController;

// use Illuminate\Support\Facades\Auth;





/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });



Route::get('/sitemap.xml', [SitemapController::class, 'index']);

// ==========================================

Route::get('/singup', [AuthController::class, 'signup'])->name('signup');
Route::post('/register', [AuthController::class, 'userRegister'])->name('userregister');

Route::get('/login', [LoginController::class, 'index'])->name('login');
Route::post('/login', [LoginController::class, 'login']);

Route::post('/logout', [LogoutController::class, 'logout'])->name('logout');


Route::get('/dashboard', [AuthController::class, 'dashboard'])->name('dashboard');

Route::get('/add-to-list/{anime_id}/{user_id}/{status}', [UserAnimeStatusListController::class, 'addToList'])->name('addToList');



Route::get('/addtofavlist/{anime_id}/{user_id}', [UserFavouriteListController::class, 'store'])->name('addtofavlist');
Route::get('/removefromfavlist/{anime_id}/{user_id}', [UserFavouriteListController::class, 'removefromfavlist'])->name('removefromfavlist');

Route::get('/addtofavlistsearchitem/{anime_id}/{user_id}', [UserFavouriteListController::class, 'searchItemFav'])->name('addtofavlistsearchitem');


Route::get('/my-list', [MyListController::class, 'index'])->name('my-list');
Route::get('/my-profile', [UserDetailController::class, 'index'])->name('my-profile');

Route::get('/blog-post', [BlogController::class, 'blogpost'])->name('blog-post');
Route::get('/blog-detail/{slug}', [BlogController::class, 'blogpostdetail'])->name('blog-detail');



Route::get('/my-review-list', [UserDetailController::class, 'userReviewList'])->name('userReviewList');
Route::get('/delete-my-review/{id}', [UserDetailController::class, 'deleteUserReview'])->name('deleteUserReview');



Route::get('/user-edit/{user_id}', [UserDetailController::class, 'userEdit'])->name('user-edit');
Route::post('/user-update/{user_id}', [UserDetailController::class, 'userUpdate'])->name('userUpdate');
Route::get('/banner-edit/{user_id}', [UserDetailController::class, 'editBannerAavatar'])->name('editBannerAavatar');
Route::post('/banner-update/{user_id}', [UserDetailController::class, 'updateBannerAvatar'])->name('bannerUpdate');





// ==========================================


Route::get('/', [HomeController::class, 'home'])->name('home');
Route::get('/redirects', [HomeController::class, 'redirects'])->name('redirects');
Route::get('/detail/{id}', [HomeController::class, 'animeDetailV2'])->name('animeDetail');

Route::get('/searchanime', [HomeController::class, 'animeSearch'])->name('searchanime');
Route::post('/search', [HomeController::class, 'searchAnime'])->name('search');

Route::get('/browse', [BrowseController::class, 'index'])->name('browse');
Route::get('/images', [BrowseController::class, 'randomImages'])->name('randomImages');

Route::get('/reviews', [ReviewsController::class, 'index'])->name('reviews');
Route::get('/review-detail/{id}', [ReviewsController::class, 'reviewDetail'])->name('reviewDeail');
Route::get('/review-add/{anime_id}', [ReviewsController::class, 'reviewAdd'])->name('reviewAdd');
Route::post('/review-store/{anime_id}/{user_id}/{user_name}', [ReviewsController::class, 'reviewStore'])->name('reviewStore');

Route::get('/anime-reviews/{anime_id}', [ReviewsController::class, 'animeReviewListing'])->name('animeReviewsListing');



Route::get('/site-stats', [SiteStatsController::class, 'index'])->name('site-stats');


// ==========================================


Route::get('/insertPopularAnime/{id}', [AnimeController::class, 'popularAnimeInsert'])->name('insertPopularAnime');
Route::get('/insertHorrorAnime/{id}', [AnimeController::class, 'horrorAnimeInsert'])->name('insertHorrorAnime');
Route::get('/insertRankedAnime/{id}', [AnimeController::class, 'rankedAnimeInsert'])->name('insertRankedAnime');
Route::get('/insert-weekly-top', [AnimeController::class, 'topAiringAnimeInsert'])->name('topAiringAnimeInsert');

// ==========================================


// admin dashboard

Route::get('/admin/login', [AdminController::class, 'loginIndex']); 

// Route::post('logout', [AdminController::class, 'logout'])->name('logout');

Route::post('/admin/login', [AdminController::class, 'login'])->name('admin-login');

Route::get('/admin/dashboard', [AdminController::class, 'dashboard'])->name('adminDashboar'); 


Route::get('/admin/blog', [BlogPostController::class, 'adminBlog'])->name('adminBlog'); 



// Route::resource('/admin/adminblogpostcategories/', CategoryController::class);
// Route::resource('category', CategoryController::class);
Route::resource('admin/adminblogcategory', CategoryController::class);
Route::resource('admin/adminblogpost', BlogPostController::class);
// ->names([
//     'index' => "blog.index"
// ]);

// Route::resource('/admin/adminblogpostcategories/', AdminBlogPostCategoryController::class);



    // Route::get('/admin/adminblogcategory', [AdminBlogCategoryController::class,'index'])->name('adminblogcategory');
    // Route::post('/admin/adminblogcategorystore', [AdminBlogCategoryController::class,'store'])->name('adminblogcategory');
    
    // Auth::routes();
// Route::group(['middleware'=>'auth'],function () {

//     // Route::get('/admin/adminblogcategory', [AdminBlogCategoryController::class,'index'])->name('adminblogcategory');
//     // Route::post('/admin/adminblogcategory', [AdminBlogCategoryController::class,'store'])->name('adminblogcategory');
    
// });

resources/views/adminDashboard/adminblogcategory/newindex.blade.php
@extends('adminDashboard.master')

@section('adminMainContent')

@section('css')
<link rel="stylesheet" href="{{ asset('sweetalert2/sweetalert2.min.css') }}">

@endsection
@section('adminMainContent')

<div class="container my-5">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-md-12" style="margin-left: 130px;">

                <div class="card product-list">
                    <div class="card-header">
                        <h4 style="float: left; margin-top:25px">Admin Blog Post Category</h4>
                        <a href="#" style="float: right;width: 260px;height: 50px;margin-top: 10px;" class="btn btn-primary"
                            data-toggle="modal" data-target="#addproduct">
                            <i class="fa fa-plus-circle fa-lg"></i> Add New Category</a>
                    </div>
                    <div class="card-body">

                        <table class="table table-bordered table-left">
                            <thead style="text-align: center;">
                                <tr>
                                    <th>ID</th>
                                    <th>Blog Post Category Name</th>
                                    <th>Created</th>
                                    <th>Updated</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody style="text-align: center;">
                                @foreach ($adminblogcategorys as $key =>$adminblogcategory)
                                <tr>
                                    <td>{{$key+1}}</td>
                                    <td>{{$adminblogcategory->name}}</td>
                                    <td>{{Carbon\Carbon::parse($adminblogcategory->created_at)->isoFormat('D-MMM-Y')}}</td>
                                    <td>{{Carbon\Carbon::parse($adminblogcategory->updated_at)->isoFormat('D-MMM-Y')}}</td>
                                    <td>    
                                        <a href="#" class="btn btn-outline-info btn-sm btn-rounded" data-toggle="modal"
                                            data-target="#editcategory{{$adminblogcategory->id}}"><i class="fa fa-edit"></i>
                                            Edit</a>

                                        <button class="btn btn-outline-danger btn-sm btn-rounded btn-delete"
                                            data-url="{{route('adminblogcategory.destroy',$adminblogcategory)}}"><i
                                                class="fas fa-trash"></i></button> 


                                    </td>
                                </tr>

                                <!-- edit supplier model -->
                                <div class="modal right fade" id="editcategory{{$adminblogcategory->id}}" data-backdrop="static"
                                    tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel"
                                    aria-hidden="true">
                                    <div class="modal-dialog" role="document" style="margin-right: 130px;">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title" id="staticBackdropLabel">Edit Category</h4>
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                                {{$adminblogcategory->id}}
                                            </div>
                                            <div class="modal-body">

                                                <form action="{{ route('adminblogcategory.update',$adminblogcategory) }}" method="POST"
                                                    enctype="multipart/form-data">
                                                    @csrf
                                                    @method('PUT')
                                                    <div class="form-group">
                                                        <label for="name">Category Name</label>
                                                        <input type="text" name="name"
                                                            class="form-control @error('name') is-invalid @enderror"
                                                            id="name" placeholder="Name"
                                                            value="{{ old('name',$adminblogcategory->name) }}">
                                                        @error('name')
                                                        <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                                        @enderror
                                                    </div>


                                                    <button class="btn btn-warning btn-block" type="submit">Update</button>
                                                </form>

                                            </div>
                                        </div>
                                    </div>
                                </div>

                                @endforeach
                            </tbody>
                        </table>
                        {{ $adminblogcategorys->render() }}

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<!-- add supplier model -->

<div class="modal right fade" id="addproduct" data-backdrop="static" tabindex="-1" role="dialog"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="margin-right: 130px;">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="staticBackdropLabel">Add Category</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <form action="{{ route('adminblogcategory.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group">
                        <label for="name">Category Name</label>
                        <input required type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                            id="name" placeholder="Name" value="{{ old('name') }}">
                        @error('full_name')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                        @enderror
                    </div>

                    <button class="btn btn-primary btn-block" type="submit">Create</button>
                </form>

            </div>
        </div>
    </div>
</div>



<style>
.modal.right .modal-dialog {
    /* position: absolute; */
    top: 0;
    right: 0;
    margin-right: 14.5vh;
}

.modal.fade:not(.in).right .modal-dialog {

    -webkit-transform: translate3d(25%, 0, 0);
    transform: translate3d(25%, 0, 0, 0);
}
</style>

<script src="{{ asset('sweetalert2/sweetalert2.all.min.js') }}"></script>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

<script>
$(document).ready(function() {
    $(document).on('click', '.btn-delete', function() {
        $this = $(this);
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-success',
                cancelButton: 'btn btn-danger'
            },
            buttonsStyling: false
        })
        swalWithBootstrapButtons.fire({
            title: 'Are you sure?',
            text: "Do you really want to delete this product?",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No',
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
                $.post($this.data('url'), {
                    _method: 'DELETE',
                    _token: '{{csrf_token()}}'
                }, function(res) {
                    $this.closest('tr').fadeOut(500, function() {
                        $(this).remove();
                    })
                })
            }
        })
    })
});

$(document).ready(function() {
    bsCustomFileInput.init();
});
</script>

@endsection